### ISSUE TITLE
Clear the bundle/project terminology in the docs

### ISSUE THREAD

**Issue by MilanKlausz** [mctools/simplebuild#44]
The new terminology of a '(package) bundle' is a bit tangled up with the older terminology of a 'project' in the documentation. 

Here's a list of related appearances of the words:
1.  The word 'project' is not defined in the [Introduction and terminology ](https://mctools.github.io/simplebuild/intro.html).
2. In the [Usage example](https://mctools.github.io/simplebuild/usage.html), the 'project directory' expression is used for the directory defined as 'package root' in the [Introduction and terminology ](https://mctools.github.io/simplebuild/intro.html).
3. In the [Installation](https://mctools.github.io/simplebuild/install.html), [Usage example](https://mctools.github.io/simplebuild/usage.html), and [The simplebuild.cfg file](https://mctools.github.io/simplebuild/simplebuilddotcfg.html), the word 'project' is used in many cases referring the the directory defined as 'bundle' / 'package bundle' in the [Introduction and terminology ](https://mctools.github.io/simplebuild/intro.html).
4. In the [Installation](https://mctools.github.io/simplebuild/install.html), dgcode is referred to as a 'set of packages'
5. The expressions: 'Projects directory' and appears in the sb command output
6. [project] and depend.projects is used in the [simplebuild.cfg](https://mctools.github.io/simplebuild/simplebuilddotcfg.html) file. (As a sidenote, depend.projects first appears in the [The \[project\] section](https://mctools.github.io/simplebuild/simplebuilddotcfg.html#the-project-section), without any hint that it will be introduced in the following 'depend' section) 
8. The possibility of grouping related packages in a common directory (formerly called 'project') is not mention explicitly (only implied in the [Package filters](https://mctools.github.io/simplebuild/simplebuilddotcfg.html#package-filters) section: "<pkgroot>/some/where/MyPkg")

**Comment by tkittel** [comment]
Agreed. I kind of knew there were some inconsistencies, but nice with a curated list :-)

**Comment by tkittel** [comment]
There is also the concept of a "master cfg" file, mentioned on https://mctools.github.io/simplebuild/simplebuilddotcfg.html but not on https://mctools.github.io/simplebuild/intro.html.

**Comment by tkittel** [comment]
I have more or less done this transition now (feel free to visit in particular the Usage and Intro pages to read), including changing the "project/projects" keywords in simplebuild.cfg (supporting the deprecated names for now, with warnings emitted).

Next is to implement corresponding changes in the downstream repos.

After this is done, simple-build-system 1.1.0 and simple-build-dgcode 1.1.0 will be the magic versions in the new world :-)

**Comment by tkittel** [comment]
Only missing item 7 in the original list, but I honestly don't think it is a big deal if we leave it out and my attempts at adding it mostly manages to make the text less easy to read. So I will ignore it for now, unless I get a PR ;-)

**Comment by tkittel** [comment]
@MilanKlausz feel free to re-read some of the pages after my changes (e.g. the usage and terminology pages), but for now I will take the liberty of closing here :-)
